services:
  ditbienbot:
    container_name: ditbienbot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data
    networks:
      - traefik_network

volumes:
  sqlite_data:
    name: ditbienbot_sqlite_data

networks:
  traefik_network:
    external: true